### ISSUE TITLE
Support for actually parsing anything?

### ISSUE THREAD

**Issue by cab404** [peti/language-nix#6]
As far as I dug through the code, it seems only capable of parsing identifiers and paths.

**Comment by sternenseemann** [comment]
This package is only intended as providing simple nix support which is enough for implementing `cabal2nix`. Thus any kind of completeness is not interesting for us, unlike other projects like [hnix](https://github.com/haskell-nix/hnix).

So, yes, we can't actually parse anything, but it's also not a goal.

**Comment by cab404** [comment]
Alright, then please express that clearly on README. `language-nix` is quite a misleading name)
