### ISSUE TITLE
Status of the repository?

### ISSUE THREAD

**Issue by thufschmitt** [peti/language-nix#8]
Hi,

As part of https://github.com/NixOS/teams-collaboration/issues/1, I am trying to clarify the status of the repositories under the NixOS organisation.

This repository seems to be unmaintained or obsolete, so it will be archived in a month.

If you think it warrants staying here or should be moved to another organization instead, please answer this issue.

**Comment by sternenseemann** [comment]
This repository has been merged into the maintained cabal2nix repository.

I'd ask that the default branch is changed to [moved](https://github.com/NixOS/language-nix/tree/moved) before archiving so that users are informed about this fact.

**Comment by thufschmitt** [comment]
Archiving the repo as indicated. Please comment on https://github.com/NixOS/teams-collaboration/issues/1 if this is a mistake.
